---
- hosts: tek
  become: true
  tasks:  
   - name: install httpd package
     yum: pkg=httpd state=latest
   - name: wait for filr to be created
     wait_for:
        path: /home/ayesha/vinumaa.log
              
         
